name: Cloud PC Setup (Windows + Tailscale + RDP + Wallpaper + Dark Mode + Auto Notepad)

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: windows-latest
    timeout-minutes: 300   # 5 hours

    steps:
      - name: Install Tailscale
        shell: powershell
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-installer.exe
          Start-Process .\tailscale-installer.exe -ArgumentList "/quiet" -Wait
          Remove-Item .\tailscale-installer.exe

      - name: Authenticate to Tailscale
        shell: powershell
        run: |
          tailscale up

      - name: Create temporary RDP/Admin user
        shell: powershell
        run: |
          $pw = [System.Web.Security.Membership]::GeneratePassword(12,2)
          Write-Host "🧑‍💻 User: clouduser"
          Write-Host "🔑 Password: $pw"

          net user clouduser $pw /add
          net localgroup Administrators clouduser /add
          net localgroup "Remote Desktop Users" clouduser /add

          Write-Host "✅ clouduser added to Administrators and Remote Desktop Users."

      - name: Apply wallpaper and dark theme for clouduser
        shell: powershell
        run: |
          $url = "https://dro.pm/cloudus"
          $wallpaperPath = "C:\Users\clouduser\wallpaper.png"
          Invoke-WebRequest $url -OutFile $wallpaperPath

          # Apply wallpaper
          Set-ItemProperty -Path 'HKCU:\Control Panel\Desktop\' -Name wallpaper -Value $wallpaperPath
          RUNDLL32.EXE user32.dll,UpdatePerUserSystemParameters

          # Enable dark mode
          $themePath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"
          New-Item -Path $themePath -Force | Out-Null
          Set-ItemProperty -Path $themePath -Name "AppsUseLightTheme" -Value 0 -Type DWord
          Set-ItemProperty -Path $themePath -Name "SystemUsesLightTheme" -Value 0 -Type DWord

      - name: Add Notepad welcome message (runs after login)
        shell: powershell
        run: |
          $msgPath = "C:\Users\clouduser\Desktop\welcome.txt"
          "ENJOY YOUR PC!" | Out-File $msgPath -Encoding UTF8

          # Auto-launch Notepad on user login
          reg load HKU\clouduser "C:\Users\clouduser\NTUSER.DAT"
          reg add "HKU\clouduser\Software\Microsoft\Windows\CurrentVersion\Run" /v WelcomeNote /t REG_SZ /d "notepad.exe $msgPath" /f
          reg unload HKU\clouduser

      - name: Keep runner alive for 5 hours
        shell: powershell
        run: |
          Start-Sleep -Seconds 18000
